pipeline {
    agent any
    
    stages {
        stage('Test') {
            steps {
                sh '/Users/dungngo.mac/Katalon\ Runtime\ Engine/execute-katalon-tests.sh'
            }
        }
    }
}
