pipeline {
    stages {
        stage('Test') {
            steps {
                sh '/Users/dungngo.mac/Katalon Runtime Engine/execute-katalon-tests.sh'
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'report/**/*.*', fingerprint: true
            junit 'report/**/JUnit_Report.xml'
        }
    }
}
